### ISSUE TITLE
Add datasource error - Testing... 

### ISSUE THREAD

**Issue by darionsr** [neuralfraud/grafana-prtg#62] opened 2017-09-27 11:00 UTC
Hello, 

I just installed grafana 4.5.2 and I tried to add a PRTG datasource, when eject "save&test", its stay in state "Testing"... Grafana (4.5.2) & PRTG (17.3.33.2830) are installed in the same server.

Has this happened to anyone?

Thanks.

![image](https://user-images.githubusercontent.com/4057778/30910038-28bb8188-a37b-11e7-8d7c-c9a717f4dc56.png)

**Comment by DiegoPeso** [comment] 2017-09-27 13:11
Hello,

I am having the same problem with Grafana (tested with 4.5.1 and 4.5.2) and PRTG 17.3.33.2830. The connection stays in "Testing...".

I have checked the packets received/sent on the PRTG server with Wireshark, and the PRTG is sending packets, answering Grafana with "Status 200 OK". Seems to be a problem with the plugin and this version of PRTG (maybe PRTG changed something in the API).

**Comment by darionsr** [comment] 2017-09-27 13:51
Oh thanks Diego! I was going crazy thinking that I do something wrong,

Thanks, I'll wait to see if they solve it.

**Comment by rvence** [comment] 2017-09-27 18:59
Same here!! Stuck on testing..

**Comment by bodforss** [comment] 2017-09-28 10:14
same here, prtg version 17.3.33.2830, grafana 4.5.2

**Comment by darionsr** [comment] 2017-09-29 07:17
Hello,

I tried the same ways, also with the IP 192.168.12.88 (my IP PRTG server). As the last test, I install PRTG and grafana in the same server, to probe that no have ports problems or similar. IP, DNS, all OK and not working. 

Thank you.

**Comment by neuralfraud** [comment] 2017-09-29 16:21
How did you obtain the passhash?

**Comment by Cool76** [comment] 2017-09-30 16:28
i got the same problem ,  I have install PRTG (version: 16.4.27.6985+) and grafana in the same server.
![1](https://user-images.githubusercontent.com/10593610/31047542-5d3ae234-a63f-11e7-967d-dc1396fbdc39.png)
![2](https://user-images.githubusercontent.com/10593610/31047543-5f8efa84-a63f-11e7-949b-5a2f36b06d55.png)

can help to fix . thx

**Comment by DiegoPeso** [comment] 2017-09-30 21:05
Hello,

I could get this info on PRTG 17.3.33.2830 and Grafana 4.5.2 over CentOS 7. My datasource details:

![captura1](https://user-images.githubusercontent.com/17882941/31049382-3b73097c-a632-11e7-80f3-3131fb0e0076.PNG)

I'm using WAMP on the same machine, running a web server, that's why i'm specifying the port 8080.

I got this info from the Chrome console:

![captura2](https://user-images.githubusercontent.com/17882941/31049407-93eb6ce8-a632-11e7-977b-9295453d1b81.PNG)

On PRTG i've created a read only user (I have checked several times that the passphrase written on Grafana is the same on PRTG):

![captura3](https://user-images.githubusercontent.com/17882941/31049423-db38d428-a632-11e7-9b9c-030bb122fa4d.png)

Running Wireshark on the PRTG server I could know that PRTG is answering correctly:

![captura4](https://user-images.githubusercontent.com/17882941/31049435-5caeafa0-a633-11e7-80ed-31bbaa69fac5.PNG)

Hope it's usefull for you, if you need any other clue tell me. Thank you so much for your job and your support.

**Comment by neuralfraud** [comment] 2017-10-01 20:36
Looks like a grafana bug. I'll test with that version and see if I can't
find the cause. I am using whatever version was released about 3 months
ago.

**Comment by DiegoPeso** [comment] 2017-10-05 13:02
Thank you so much! :)

**Comment by themcv** [comment] 2017-10-10 11:52
Any update on this? Hoping to get this working by the end of the week, but no rush. :)

**Comment by helenes-r7** [comment] 2017-10-18 19:44
I am also running into this problem. Thanks so much for this plugin too!

**Comment by bthresher183** [comment] 2017-10-20 14:02
Same Here. Grafana 4.5.0 (CentOS Linux release 7.3.1611 (Core)). Would LOVE to get this working. Right now, we have designed our own program to do basically the same thing, but this looks much more refined. 

My data source settings 100% match what is in the install guide, except for the PRTG IP, User. and Pass hash. Just sits at testing. No error in development tools in Chrome. Let me know if you need any info from me, I would be glad to help.

**Comment by Klmakke** [comment] 2017-10-20 14:37
Hello,

Same problem here. This looks like a great and very promising plugin would love to see it in action! Thank you!

Grafana v4.5.2
PRTG 17.3.35 also tried with the stable 17.3.33

**Comment by martinohansen** [comment] 2017-10-23 07:48
It seems we are having the same issue

**Comment by DiegoPeso** [comment] 2017-10-27 18:08
Datasource connection working correctly on Grafana 4.6.

I haven't try yet to do a dashboard.

**Comment by neuralfraud** [comment] 2017-10-27 19:08
I apologize for the late response, since I've been looking for new work the last couple of weeks. 

This works fine in Grafana 4.6.0. 

If 4.5.2 doesn't work, either downgrade to 4.4 or upgrade to 4.6. 

closing the issue.

**Closed by neuralfraud** 2017-10-27 19:08 UTC
