### ISSUE TITLE
Cannot read property 'q' of undefined

### ISSUE THREAD

**Issue by kinomakino** [neuralfraud/grafana-prtg#29] opened 2017-01-26 20:06 UTC
First of all, thanks for this amazing proyect.

This error is when select a simple metric from prtg: sensor ping.
Thanks !!!

TypeError: Cannot read property 'q' of undefined
    at eval (http://127.0.0.1:12345/public/plugins/jasonlashua-prtg-datasource/datasource.js?bust=1485460741385:114:45)
    at l (http://127.0.0.1:12345/public/app/boot.js:52:14654)
    at Function.Sg [as map] (http://127.0.0.1:12345/public/app/boot.js:53:15348)
    at PRTGDataSource.query (http://127.0.0.1:12345/public/plugins/jasonlashua-prtg-datasource/datasource.js?bust=1485460741385:98:42)
    at b.issueQueries (http://127.0.0.1:12345/public/app/boot.js:46:4632)
    at b.issueQueries (http://127.0.0.1:12345/public/app/boot.js:19:2788)
    at g (http://127.0.0.1:12345/public/app/boot.js:42:13902)
    at http://127.0.0.1:12345/public/app/boot.js:42:14074
    at o.$eval (http://127.0.0.1:12345/public/app/boot.js:42:21715)
    at o.$digest (http://127.0.0.1:12345/public/app/boot.js:42:20201)

**Comment by neuralfraud** [comment] 2017-02-18 20:50
Caused by broken code. Master branch now  updated and works with 4.1+; closing issue. THANK YOU!

**Closed by neuralfraud** 2017-02-18 20:50 UTC
