### ISSUE TITLE
Unauthorised Error with PRTG

### ISSUE THREAD

**Issue by robertholz** [neuralfraud/grafana-prtg#31] opened 2017-02-20 16:26 UTC
Hi, 

I am getting the following error with all sensors in the latest version of this PRTG plugin

Unknown error: <HTML><BODY><B>Unauthorized</B></BODY></HTML>

I have looked and can confirm the username and passhash I am using is correct

Many thanks, 
Rob

**Comment by neuralfraud** [comment] 2017-02-20 16:28
This is due to a change in the authentication. The plugin now uses Passhash instead of the password. I will make sure to update the documentation for this ASAP.

**Comment by robertholz** [comment] 2017-02-20 16:33
Hi,

I am using the passhash though

Many thanks,
Rob

**Comment by robertholz** [comment] 2017-02-20 16:36
Also, the error is this (github formats it incorrectly)

`Unknown error: <HTML><BODY><B>Unauthorized</B></BODY></HTML>`

**Comment by neuralfraud** [comment] 2017-02-20 16:41
So when you "Save and test" connection, it pops up an orange box and says Unauthorized? And have you opened the developer console of the browser to see the error message and/or network request? 

Can you show me a screenshot of the config page for the datasource?

**Comment by robertholz** [comment] 2017-02-20 16:43
Grafana connects successfully when creating a PRTG datasource

The issue is with Grafana then loading stats from PRTG, please see the attatched screenshot
![grafanascreenshot](https://cloud.githubusercontent.com/assets/25103587/23134166/b47b62b6-f78b-11e6-9915-cbadb9de0009.png)

**Comment by neuralfraud** [comment] 2017-02-20 16:51
Ok that's strange. You only have the one data source, right? have you tried to edit a panel and re-select the metric datasource? the only way to know for sure is to see the traffic log using the developer tools. You should be able to see the full request which includes username and passhash values, you should be able to tell if it's sending the right data across...

**Comment by robertholz** [comment] 2017-02-20 16:54
I have only that datasource, when I try to re-edit the panel I get the following error

![snip_20170220165305](https://cloud.githubusercontent.com/assets/25103587/23134530/0fdb2da2-f78d-11e6-8140-3e18868dd472.png)

For some reason, everything seems to be working now, maybe PRTG takes a while to update account passwords

**Comment by neuralfraud** [comment] 2017-02-20 17:58
So after the unauthorized issue went away, it works, the channel list is populating and everything is ok now?

**Comment by tsdevelop** [comment] 2017-02-22 10:41
Hello neuralfraud, i'm getting the same error. 401: Unauthorized with a red box in background. I deleted all panels and added a new one and there i cant choose probes. Im getting only *. Problem is not solved.
![image](https://cloud.githubusercontent.com/assets/25952560/23207993/9b5baa0c-f8f3-11e6-8f14-f2c699c003e6.png)
![image](https://cloud.githubusercontent.com/assets/25952560/23208024/c03558be-f8f3-11e6-8b25-9629ebdb077d.png)
![image](https://cloud.githubusercontent.com/assets/25952560/23208050/db3ebcb8-f8f3-11e6-9a4c-26d1c3866f65.png)

**Comment by neuralfraud** [comment] 2017-02-22 12:26
Why is "Basic Auth" checked??

**Comment by tsdevelop** [comment] 2017-02-22 12:41
I thougt it must be checked. i have uncked now but its the same problem. Or do i have to check samthing else ?

**Comment by tsdevelop** [comment] 2017-02-22 15:14
After i created my passhash i can successfully test & save the connection but i cant choose a probe. it is only * with error: Unauthorized

**Comment by neuralfraud** [comment] 2017-02-22 15:47
@tsdevelop 

@robertholz has the same issue and suddenly it went away. I really have no idea why it isn't working. I have to assume that you've got a standard copy of Grafana and the plugin is installed, cleanly, into the correct folder (seems to be), and the only other thing I can think of is the browser... 

Have you tried simply cleaning the cache, etc? Are you running the latest version from the master branch?

**Comment by darinarrick** [comment] 2017-02-22 17:09
In response to your question in #27, that line you have quoted is on line 92 of PRTGAPIService.js, not 106. I git cloned, so timestamps are when I did that. Should I have installed it differently? Could that be the issue?

**Comment by darinarrick** [comment] 2017-02-22 17:22
So, I was wrong. I'd swear I installed Grafana 4.1.2, but:

"Grafana v4.1.1 (commit: v4.1.1)"

I'll see if I can update it.

**Comment by neuralfraud** [comment] 2017-02-22 17:28
@darinarrick Yes, ok I must have been looking at src/PRTGAPIService.js. anyhow. Since I've been unable to even remotely guess as to why this happens, I need some info:

- PRTG Version
- Grafana Version
- OS that grafana runs under, location of plugin
- Browser, browser version

Also, some troubleshooting questions: 

- did you clear cache?
- did you stop/restart grafana server after updating plugin?
- have you tried to update the plugin by completely wiping the existing **jasonlashua-prtg-datasource** folder? 
- can you confirm that the datasource settings save & test config works? 
- have you tried creating a new, blank dashboard?

**Comment by neuralfraud** [comment] 2017-02-22 17:29
I'll see what happens with 4.1.1

**Comment by darinarrick** [comment] 2017-02-22 17:41
PRTG 17.1.28.1032+
Grafana 4.1.2 (I just updated it; I used "yum install https://grafanarel.s3.amazonaws.com/builds/grafana-4.1.2-1486989747.x86_64.rpm" )
Linux itweb.ourdomain.com 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Chrome 56.0.2924.87 (the latest one)

I have not cleared browser cache yet.
I did restart, multiple times.
Since I did the Grafana 4.1.2 yum install, I'm going to have to reinstall your plugin, so yes, that will happen.

Will report back.

**Comment by neuralfraud** [comment] 2017-02-22 18:00
@darinarrick Very interesting.. I installed grafana 4.1.2 RPM onto a CentOS server here, started, stopped service.. Copied my plugin jasonlashua-prtg-datasource to /var/lib/grafana/plugins and started grafana.

I was able to successfully configure the datasource, but notice firstly that some images did not show up. 
I then went and added a  new dashboard and saw the same issue

The browser sends a request and to https://prtg.site.com/api/table.json?username=grafana&passhash=[object%20Object]....

I then hit Shift-F5 and the damn thing worked.

**Comment by darinarrick** [comment] 2017-02-22 18:42
I did the same thing. Once, it pulled the main group and "*"; since then, it hasn't. I've tried two browsers: Chrome and Firefox. I see in the dev console:

10:39:06.817 Potentially unhandled rejection [7] performPRTGAPIRequest/<@http://grafana:3000/public/plugins/jasonlashua-prtg-datasource/PRTGAPIService.js?bust=1487788733088:132:1
g@http://grafana:3000/public/app/boot.6d63bd8b.js:42:13902
h/<@http://grafana:3000/public/app/boot.6d63bd8b.js:42:14074
xc/this.$get</o.prototype.$eval@http://grafana:3000/public/app/boot.6d63bd8b.js:42:21711
xc/this.$get</o.prototype.$digest@http://grafana:3000/public/app/boot.6d63bd8b.js:42:20193
xc/this.$get</o.prototype.$apply@http://grafana:3000/public/app/boot.6d63bd8b.js:42:21996
x/i<@http://grafana:3000/public/app/boot.6d63bd8b.js:42:18162
f@http://grafana:3000/public/app/boot.6d63bd8b.js:40:31993
jb/k.defer/c<@http://grafana:3000/public/app/boot.6d63bd8b.js:41:1437
1 boot.6d63bd8b.js:5:27824
[4]</</</</k<() boot.6d63bd8b.js:5
f() boot.6d63bd8b.js:5
i() boot.6d63bd8b.js:5

**Comment by darinarrick** [comment] 2017-02-22 18:44
I'm using the data source direct to the /api/ URL with username and passhash and a short cache timeout of a minute.

Hrm... I just tried to save and test the datasource. Didn't change a single thing; I just went into the datasources, chose it, looked at it, and hit "Save and Test". Now it's getting "undefined:undefined" instead of the PRTG version number.

**Comment by darinarrick** [comment] 2017-02-22 18:49
Yeah, whatever the problem is seems to be that "unhandled rejection". I did just get this new item in the dev console in Chrome:

Data source query result invalid, missing data field: Array[0]length: 0__proto__: Array[0]

I had deleted and readded the data source. It got the version correctly. Then I created a new dashboard and tried to add a graph. No groups showed, only "*".

**Comment by neuralfraud** [comment] 2017-02-22 18:56
On any grafana install, after updating the datasource you go to a dashboard and you see "Unauthorized"

if you look at the developer console of the browser, you can see those HTTP 401 unauthorized messages, Upon examination of the URI, you can see "username=someuser&passhash=[object%20Object]" ..

**Pressing F5 or clicking the Refresh button appears to resolve the issue.**

@darinarrick Go to the datasource page, press Save & Test, if green, go to a dashboard... if you see the error markers, etc, hit F5. What happens?

**Comment by darinarrick** [comment] 2017-02-22 19:04
I created a new dashboard and tried to add a Graph. Go to edit. Metrics. Change data source to the added PRTG data source. Main group didn't appear. F5 refresh. Now I get the main group in the "Group" field, but only "*" in the other three fields.

**Comment by neuralfraud** [comment] 2017-02-22 19:21
The requests are async and may take a while to load, click another field and go back...what happens? without even having a group selected, you should see all devices. if nothing, using developer console F12, go to the network tab and look for requests like "table.json?username=grafana&passhash=1234567890&content=devices"
Click the request and look to the right under the "Response" tab, copy and paste what you see.

**Comment by darinarrick** [comment] 2017-02-22 19:30
https://dcvbtmon/api/table.json?username=grafana&passhash=4264292775&content=groups&columns=objid,group
{"prtg-version":"17.1.28.1032","treesize":1,"groups":[{"objid":0,"group":"VoiceBox IT"}]}

https://dcvbtmon/api/table.json?username=grafana&passhash=4264292775&content=devices&columns=objid,device
{"prtg-version":"17.1.28.1032","treesize":0,"devices":[]}

https://dcvbtmon/api/table.json?username=grafana&passhash=4264292775&content=sensors&columns=objid,sensor,device,group&filter_device=undefined
{"prtg-version":"17.1.28.1032","treesize":0,"sensors":[]}

**Comment by neuralfraud** [comment] 2017-02-22 19:33
First the group query you have one group, VoiceBox IT. However, there are no devices... the tree is empty.

**Comment by darinarrick** [comment] 2017-02-22 20:17
That is correct. And none of the other nodes ever load. See the comment in #27 where I gave the organization of our PRTG items.

**Comment by neuralfraud** [comment] 2017-02-22 20:31
@darinarrick  the group in which your grafana user exists does not have permissions on the objects. That is why they aren't showing. The previous demonstration shows that you've made a successful call to the API, and that the API had zero objects to give.

# Establishing permissions for your grafana user account

1. Identify the primary group in which the api user account resides, for instance, PRTG Users Group
2. click the "**Settings**" tab in your Devices view and scroll down to the "**Access Rights**" section.
3. In the below table, change the access for the individual user group from "None" to "Read"
4. Grafana will now work.

**Comment by neuralfraud** [comment] 2017-02-22 20:34
# Resolving "Unknown error: Unauthorized" Messages After Upgrading Plugin with Grafana 4.x.x

This seems to be an issue with Grafana. The cause is unknown, however a workaround exists:

- Open the Datasource Settings
- click the **Save & Test Connection **" button.
- If the test is successful, go back to a dashboard.
- Hit the Refresh button or the F5 key - the content should now display.

**Comment by darinarrick** [comment] 2017-02-22 20:49
I fixed the permissions for that PRTG user group (I had assumed they were set correctly; they were not). I tried; no change. I deleted and re-added the data source. No results at first. Then I did the page refresh and it worked! I have successfully added a channel from a sensor and made a graph.

**Closed** 2017-02-22 21:03 UTC
Labels: question

**Comment by augustomolinap** [comment] 2019-04-02 15:21
Hi neuralfraud.
I'm having a similar issue as darinarrick. But what is happening to me is that when grafana tries to get the devices from PRTG it is not including the passhash:
http://10.128.11.133:3000/api/datasources/proxy/2/table.json?username=amolina&passhash=[object%20Object]&content=sensors&count=9999&columns=objid,sensor,device,group,probe,tags,active,status,message,priority&
if I manually modify it and put the passhash there, i get some data but it gets a "SyntaxError: JSON.parse: unterminated string at line 1 column 1048577 of the JSON data" If I make the query on the browser i receive the whole answer but it seems that on grafana the response gets trunkated.
Thanks in advance.

**Comment by cburkins** [comment] 2019-12-09 22:12
Was having the same issue, creating the data source worked and provided back the PRTG version, but when I went to populate a new query/visualization, I got Unauthorized.   By reloading that particular browser tab, all is working now.

**Comment by yurividal** [comment] 2020-04-30 09:20
Clearing the browser cache and refreshing the page solved for me too.
