### ISSUE TITLE
Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by Abolah** [neuralfraud/grafana-prtg#44] opened 2017-06-28 09:11 UTC
Hello,
I encountered this error after adding the PRTG DataSource to my grafan installation.

![image](https://user-images.githubusercontent.com/10921309/27629379-6ee02c48-5bf2-11e7-8780-2f3eecc05e92.png)

I'm using Grafana 4.3.2 and PRTG API version: 17.1.28.1032+

Can you help me fix this ?

**Comment by Abolah** [comment] 2017-06-28 09:25
I forgot to mention i'm using PRTG API version: 17.1.28.1032+

**Comment by g3rhard** [comment] 2017-07-11 03:58
Hello, i think, i have the same issue, periodically i see that message.
![screenshot_12](https://user-images.githubusercontent.com/8848216/28050371-da080b84-662f-11e7-97e2-a8378fbae711.png)
Grafana 4.3.1 PRTG API version: 16.4.27.7140+

**Comment by packtman** [comment] 2017-07-13 16:05
@neuralfraud I am facing the same error. 'Cannot read property 'objid' of undefined'. Can you please have a look at it.

![2017-07-13 12_02_47-grafana - sensor](https://user-images.githubusercontent.com/7194155/28175916-9d10bcf4-67c3-11e7-89b6-5d98891219ec.png)

**Comment by neuralfraud** [comment] 2017-07-13 18:27
Cant read objid means an uncessful query - i.e. narrow time range, or bad query, or use of the "!" channel which is just plain buggy (i know)

**Comment by packtman** [comment] 2017-07-13 18:36
I am using the PRTG-Veeam Script by Markus: https://github.com/mycloudrevolution/Advanced-PRTG-Sensors/blob/master/Veeam/PRTG-VeeamBRStats.ps1

https://kb.paessler.com/en/topic/72030-monitoring-veeam-backup-replication-without-veeam-enterprise-manager

Other script of his is working fine: https://kb.paessler.com/en/topic/72033-monitoring-veeam-backup-replication-using-veeam-enterprise-manager

**Comment by neuralfraud** [comment] 2017-07-15 23:35
@packtman I will check out that Veeam script and let you know how it works. Give the [Development branch](https://github.com/neuralfraud/grafana-prtg/tree/Development) a try though, many fixes. Should be a direct drop in replacement (remove the old "jasonlashua-prtg-datasource" directory first!)

**Comment by neuralfraud** [comment] 2017-07-15 23:39
@Abolah Hi, this is caused by a bug in the code, it's supposed to display an error from the PRTG api, but my code sucks, so it just throws an exception instead. If I come across it again I'll try to fix it.

**Comment by neuralfraud** [comment] 2017-07-15 23:41
@g3rhard based on the line of code, it looks like it is doing the "get sensor by name" routine, and expecting a sensor item to be present, there is no sensor item present. What was the sensor you had selected in the query that resulted in that message?

**Comment by neuralfraud** [comment] 2017-07-15 23:42
This looks like a couple of separate bugs. 

the "cannot read 'objId' of undefined issue should be fixed in the [Development branch](https://github.com/neuralfraud/grafana-prtg/tree/Development). The "property match of 'undefined'" issue however, still remains.

I will update master once I've conducted thorough testing of the development code in a production setting.

**Comment by packtman** [comment] 2017-07-17 14:53
@neuralfraud previously with the 'Cannot read property 'objid' of undefined' I wasn't able to see metrics under Channel. Now, after updating to latest release I am able to see metrics under channel, but along with a new error: 'Cannot read property 'length' of undefined'
![2017-07-17 10_43_25-grafana - sensor](https://user-images.githubusercontent.com/7194155/28273941-91320b96-6add-11e7-88e2-04b123b75c89.png)

**Comment by neuralfraud** [comment] 2017-07-18 02:59
This is closed. Version 4.0 is now in the master branch. Upgrade today!

**Closed by neuralfraud** 2017-07-18 02:59 UTC
Labels: bug
