### ISSUE TITLE
Unable to add datasource

### ISSUE THREAD

**Issue by Saviger** [neuralfraud/grafana-prtg#43] opened 2017-06-07 20:01 UTC
I am unable to add the datasource, getting a 404 error for the *.js files.

![image](https://user-images.githubusercontent.com/29262141/26898515-4916f4a0-4b9a-11e7-8428-5aeb83233c68.png)

from the log file:
path=/public/app/plugins/datasource/jasonlashua-prtg-datasource/module.js status=404

EDIT:
I attempted the log-out log-in fix mentioned by a closed issue. This did not work for me. =(

**Comment by ruudmens** [comment] 2017-06-12 07:00
Did you check if module.js is in the correct (mentioned) folder?

**Comment by neuralfraud** [comment] 2017-07-17 04:35
Your plugins belong in the "{GRAFANA_HOME}/data/plugins" directory. the tree should look like this:
![image](https://user-images.githubusercontent.com/8482103/28255659-c23fa41a-6a87-11e7-90ba-63e88cb50cfb.png)

Closing because not a bug.

**Closed by neuralfraud** 2017-07-17 04:35 UTC
